SELECT
    month,
    organization_id,
    organization_name,
    organization_business_os_type,
    organization_industry,
    organization_employee_count,
    organization_size_cohort,
    organization_status_current,
    organization_plan_name_current,
    organization_status,
    organization_is_churned,
    organization_churned_at,
    organization_is_churned_in_month,
    subscription_change_reason,
    total_mrr_amount,
    total_mrr_amount - LAG(total_mrr_amount) OVER(PARTITION BY organization_id ORDER BY month) AS mom_total_mrr_delta,
    total_seats,
    total_seats - LAG(total_seats) OVER(PARTITION BY organization_id ORDER BY month) AS mom_total_seats_delta,
    num_events,
    num_events - LAG(num_events) OVER(PARTITION BY organization_id ORDER BY month) AS mom_num_events_delta,
    num_rocks,
    num_rocks - LAG(num_rocks) OVER(PARTITION BY organization_id ORDER BY month) AS mom_num_rocks_delta,
    num_issues,
    num_issues - LAG(num_issues) OVER(PARTITION BY organization_id ORDER BY month) AS mom_num_issues_delta,
    num_meetings,
    num_meetings - LAG(num_meetings) OVER(PARTITION BY organization_id ORDER BY month) AS mom_num_meetings_delta,
    num_scorecards,
    num_scorecards - LAG(num_scorecards) OVER(PARTITION BY organization_id ORDER BY month) AS mom_num_scorecards_delta,
    num_todos,
    num_todos - LAG(num_todos) OVER(PARTITION BY organization_id ORDER BY month) AS mom_num_todos_delta,
    num_headlines,
    num_headlines - LAG(num_headlines) OVER(PARTITION BY organization_id ORDER BY month) AS mom_num_headlines_delta
FROM {{ ref('int_monthly_organization_activity') }}